/**
 * Ánh xạ: tên icon dùng trong app  ->  [nguồn, tên file trong bộ icon]
 *
 *   'h' = heroicons   (có sẵn cả outline 24 lẫn solid 20)
 *   'l' = lucide      (chỉ dùng cho những icon Heroicons không có:
 *                      tractor, bike, leaf, droplet, factory, gauge,
 *                      headset, gem, toggle, handshake, award...)
 *
 * Key giữ nguyên tên cũ theo Material Icons để dữ liệu icon trong các file
 * .ts (menu admin, dashboard, section trang chủ) không phải đổi theo.
 */
export const ICON_MAP = {
  add: ['h', 'plus'],
  agriculture: ['l', 'tractor'],
  apartment: ['h', 'building-office-2'],
  archive: ['h', 'archive-box'],
  arrow_back: ['h', 'arrow-left'],
  arrow_forward: ['h', 'arrow-right'],
  attach_file: ['h', 'paper-clip'],
  battery_charging_full: ['l', 'battery-charging'],
  block: ['h', 'no-symbol'],
  bolt: ['h', 'bolt'],
  build: ['h', 'wrench-screwdriver'],
  business: ['h', 'building-office'],
  calendar_month: ['h', 'calendar-days'],
  calendar_today: ['h', 'calendar'],
  call_split: ['l', 'git-fork'],
  category: ['h', 'squares-2x2'],
  check: ['h', 'check'],
  check_box: ['l', 'square-check'],
  check_circle: ['h', 'check-circle'],
  chevron_right: ['h', 'chevron-right'],
  close: ['h', 'x-mark'],
  cloud_upload: ['h', 'cloud-arrow-up'],
  content_copy: ['h', 'document-duplicate'],
  credit_card: ['h', 'credit-card'],
  delete: ['h', 'trash'],
  description: ['h', 'document-text'],
  diamond: ['l', 'gem'],
  eco: ['l', 'leaf'],
  edit: ['h', 'pencil-square'],
  electric_moped: ['l', 'bike'],
  emoji_events: ['h', 'trophy'],
  event_available: ['l', 'calendar-check'],
  expand_more: ['h', 'chevron-down'],
  factory: ['l', 'factory'],
  favorite: ['h', 'heart'],
  forum: ['h', 'chat-bubble-left-right'],
  fullscreen: ['h', 'arrows-pointing-out'],
  grid_view: ['h', 'squares-2x2'],
  group: ['h', 'user-group'],
  handshake: ['l', 'handshake'],
  handyman: ['h', 'wrench'],
  headset_mic: ['l', 'headset'],
  help_outline: ['h', 'question-mark-circle'],
  history: ['l', 'history'],
  home: ['h', 'home'],
  image: ['h', 'photo'],
  inbox: ['h', 'inbox'],
  info: ['h', 'information-circle'],
  inventory_2: ['l', 'package'],
  key: ['h', 'key'],
  lightbulb: ['h', 'light-bulb'],
  list: ['h', 'list-bullet'],
  local_offer: ['h', 'tag'],
  local_shipping: ['h', 'truck'],
  login: ['h', 'arrow-right-end-on-rectangle'],
  logout: ['h', 'arrow-right-start-on-rectangle'],
  mail: ['h', 'envelope'],
  mail_outline: ['h', 'envelope'],
  menu: ['h', 'bars-3'],
  menu_open: ['h', 'bars-3-bottom-left'],
  notifications: ['h', 'bell'],
  open_in_new: ['h', 'arrow-top-right-on-square'],
  payments: ['h', 'banknotes'],
  pedal_bike: ['l', 'bike'],
  person_add: ['h', 'user-plus'],
  phone: ['h', 'phone'],
  phone_in_talk: ['h', 'phone-arrow-up-right'],
  photo_library: ['h', 'photo'],
  place: ['h', 'map-pin'],
  refresh: ['h', 'arrow-path'],
  rocket_launch: ['h', 'rocket-launch'],
  route: ['l', 'route'],
  schedule: ['h', 'clock'],
  search: ['h', 'magnifying-glass'],
  sell: ['h', 'tag'],
  settings: ['h', 'cog-6-tooth'],
  speed: ['l', 'gauge'],
  star: ['h', 'star'],
  toggle_off: ['l', 'toggle-left'],
  toggle_on: ['l', 'toggle-right'],
  tune: ['h', 'adjustments-horizontal'],
  two_wheeler: ['l', 'bike'],
  verified: ['h', 'check-badge'],
  verified_user: ['h', 'shield-check'],
  view_in_ar: ['h', 'cube'],
  visibility: ['h', 'eye'],
  visibility_off: ['h', 'eye-slash'],
  warning: ['h', 'exclamation-triangle'],
  water_drop: ['l', 'droplet'],
  workspace_premium: ['l', 'award'],
};
