// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20260923003158_AddElectricalApplianceProducts")]
    partial class AddElectricalApplianceProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.AgriculturalMachineProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Capacity")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Compatibility")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineType")
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .HasColumnType("text");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Power")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CompanyId");

                    b.ToTable("AgriculturalMachineProducts");
                });

            modelBuilder.Entity("Core.Entities.Brand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = "brand-seed-electrical-001",
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thương hiệu mẫu cho danh mục đồ điện gia dụng.",
                            IsUsed = true,
                            LogoUrl = "/assets/images/img-ph.jpg",
                            Metadata = "{}",
                            Name = "Điện Cơ Việt",
                            UpdatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Core.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = "company-seed-electrical-001",
                            Address = "Việt Nam",
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đơn vị phân phối thiết bị điện cơ và điện dân dụng.",
                            Email = "dienco@example.com",
                            IsUsed = true,
                            LogoUrl = "/assets/images/img-ph.jpg",
                            Metadata = "{}",
                            Name = "Điện Cơ Dân Dụng Việt",
                            PhoneNumber = "0900000000",
                            UpdatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = ""
                        });
                });

            modelBuilder.Entity("Core.Entities.ElectricBikeProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BatteryCapacity")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Compatibility")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Power")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Voltage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CompanyId");

                    b.ToTable("ElectricBikeProducts");
                });

            modelBuilder.Entity("Core.Entities.ElectricalApplianceProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Capacity")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Compatibility")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Power")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Voltage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CompanyId");

                    b.ToTable("ElectricalApplianceProducts");

                    b.HasData(
                        new
                        {
                            Id = "ea000001-0000-0000-0000-000000000301",
                            Brand = "Điện Cơ Việt",
                            BrandId = "brand-seed-electrical-001",
                            Capacity = "8 lít/phút",
                            CompanyId = "company-seed-electrical-001",
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sản phẩm mẫu thuộc nhóm Máy rửa xe.",
                            IsUsed = true,
                            Metadata = "{\"warrantyMonths\":\"12\"}",
                            Model = "RX-1800",
                            Name = "Máy rửa xe",
                            PictureUrl = "/assets/images/img-ph.jpg",
                            Power = "1800W",
                            Price = 2490000m,
                            StockQuantity = 12,
                            Type = "PressureWasher",
                            UpdatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = "220V"
                        },
                        new
                        {
                            Id = "ea000002-0000-0000-0000-000000000302",
                            Brand = "Điện Cơ Việt",
                            BrandId = "brand-seed-electrical-001",
                            CompanyId = "company-seed-electrical-001",
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sản phẩm mẫu thuộc nhóm Dụng cụ cầm tay.",
                            IsUsed = true,
                            Metadata = "{\"warrantyMonths\":\"12\"}",
                            Model = "DCT-21V",
                            Name = "Dụng cụ cầm tay",
                            PictureUrl = "/assets/images/img-ph.jpg",
                            Power = "650W",
                            Price = 1290000m,
                            StockQuantity = 25,
                            Type = "HandTool",
                            UpdatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = "21V"
                        },
                        new
                        {
                            Id = "ea000003-0000-0000-0000-000000000303",
                            Brand = "Điện Cơ Việt",
                            BrandId = "brand-seed-electrical-001",
                            CompanyId = "company-seed-electrical-001",
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sản phẩm mẫu thuộc nhóm Máy xây dựng.",
                            IsUsed = true,
                            Metadata = "{\"warrantyMonths\":\"12\"}",
                            Model = "MXD-2200",
                            Name = "Máy xây dựng",
                            PictureUrl = "/assets/images/img-ph.jpg",
                            Power = "2200W",
                            Price = 5890000m,
                            StockQuantity = 7,
                            Type = "ConstructionMachine",
                            UpdatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = "220V"
                        },
                        new
                        {
                            Id = "ea000004-0000-0000-0000-000000000304",
                            Brand = "Điện Cơ Việt",
                            BrandId = "brand-seed-electrical-001",
                            CompanyId = "company-seed-electrical-001",
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sản phẩm mẫu thuộc nhóm Mô Tơ.",
                            IsUsed = true,
                            Metadata = "{\"warrantyMonths\":\"12\"}",
                            Model = "MT-3HP",
                            Name = "Mô Tơ",
                            PictureUrl = "/assets/images/img-ph.jpg",
                            Power = "3HP",
                            Price = 3450000m,
                            StockQuantity = 10,
                            Type = "Motor",
                            UpdatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = "220V"
                        },
                        new
                        {
                            Id = "ea000005-0000-0000-0000-000000000305",
                            Brand = "Điện Cơ Việt",
                            BrandId = "brand-seed-electrical-001",
                            Capacity = "30 lít/phút",
                            CompanyId = "company-seed-electrical-001",
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sản phẩm mẫu thuộc nhóm Máy Bơm.",
                            IsUsed = true,
                            Metadata = "{\"warrantyMonths\":\"12\"}",
                            Model = "MB-125",
                            Name = "Máy Bơm",
                            PictureUrl = "/assets/images/img-ph.jpg",
                            Power = "125W",
                            Price = 2190000m,
                            StockQuantity = 15,
                            Type = "WaterPump",
                            UpdatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = "220V"
                        },
                        new
                        {
                            Id = "ea000006-0000-0000-0000-000000000306",
                            Brand = "Điện Cơ Việt",
                            BrandId = "brand-seed-electrical-001",
                            Capacity = "45Ah",
                            CompanyId = "company-seed-electrical-001",
                            CreatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sản phẩm mẫu thuộc nhóm Ắc quy các loại.",
                            IsUsed = true,
                            Metadata = "{\"warrantyMonths\":\"12\"}",
                            Model = "AQ-12V",
                            Name = "Ắc quy các loại",
                            PictureUrl = "/assets/images/img-ph.jpg",
                            Price = 1850000m,
                            StockQuantity = 20,
                            Type = "Battery",
                            UpdatedAt = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = "12V"
                        });
                });

            modelBuilder.Entity("Core.Entities.EntityImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.ToTable("EntityImages");
                });

            modelBuilder.Entity("Core.Entities.AgriculturalMachineProduct", b =>
                {
                    b.HasOne("Core.Entities.Brand", "BrandEntity")
                        .WithMany("AgriculturalMachineProducts")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Company", "Company")
                        .WithMany("AgriculturalMachineProducts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandEntity");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Entities.ElectricBikeProduct", b =>
                {
                    b.HasOne("Core.Entities.Brand", "BrandEntity")
                        .WithMany("ElectricBikeProducts")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Company", "Company")
                        .WithMany("ElectricBikeProducts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandEntity");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Entities.ElectricalApplianceProduct", b =>
                {
                    b.HasOne("Core.Entities.Brand", "BrandEntity")
                        .WithMany("ElectricalApplianceProducts")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Company", "Company")
                        .WithMany("ElectricalApplianceProducts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandEntity");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Entities.Brand", b =>
                {
                    b.Navigation("AgriculturalMachineProducts");

                    b.Navigation("ElectricBikeProducts");

                    b.Navigation("ElectricalApplianceProducts");
                });

            modelBuilder.Entity("Core.Entities.Company", b =>
                {
                    b.Navigation("AgriculturalMachineProducts");

                    b.Navigation("ElectricBikeProducts");

                    b.Navigation("ElectricalApplianceProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
